### ISSUE TITLE
ansible provisioner: * translation missing: en.vagrant.provisioners.ansible.playbook_path_invalid * translation missing: en.vagrant.provisioners.ansible.playbook_path_invalid

### ISSUE THREAD

**Issue by mevam** [damok6/vagrant-ansible-mesos-marathon-cluster#2]
ansible provisioner:
* translation missing: en.vagrant.provisioners.ansible.playbook_path_invalid
* translation missing: en.vagrant.provisioners.ansible.playbook_path_invalid
Sorry, what is the reason for this?

**Comment by mevam** [comment]
Sorry, resolved

**Comment by damok6** [comment]
Hi Mevam, that's good news. Out of curiosity, what was the problem? Is there something that can be reproduced and made easier to avoid in the future?
